@url = http://localhost:7071/api 
@email = m8ceg.delacruzhome@inbox.testmail.app 
@contentType = application/json

POST {{url}}/NewsletterSubscriber
Content-Type: {{contentType}}

{
    "email": "{{email}}"
}